services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Oveleon\ProductInstaller\:
        resource: '../../'
        exclude: '../../{Model,DependencyInjection,Resources,Licenser}'
