services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Oveleon\ProductInstaller\:
        resource: '../src/'
        exclude: '../src/{Model,DependencyInjection,Resources,LicenseConnector,Import/Prompt,Import/Validator.php}'
